---
metadata:
  name: Futureworks
  short_name: Paperworks
  description: Futureworks - Learn you the software craftsmanship
  language: en
  pathPrefix: "/"
  siteImage:
  favicon: "/assets/favicon.png"
  themeColor: "#ff0000"
header:
  enabled: true
  logo: "/assets/code.svg"
  logoLink: "/"
  helpUrl: ""
  links:
    - text: BooGi
      link: https://github.com/filipowm/boogi
      external: true
    - text: Gatsby
      link: https://www.gatsbyjs.org
      external: true
    - text: Docs
      link: "/"
      external: false
sidebar:
  enabled: true
  # forcedNavOrder:
  #   - "/introduction"
  #   - "/configuration/basic"
  #   - "/configuration/advanced"
  # expanded:
  groups:
    - order: 1
      path: "/fondamentaux"
      title: ":rocket: Fondamentaux"
    - order: 2
      path: "/code"
      title: ":computer: Dans le code"
    - order: 3
      path: "/tests"
      title: ":writing_hand: Dans les tests"
    - order: 4
      path: "/softskills"
      title: ":medal: Au quotidien"
  links:
    - text: BooGi
      link: https://github.com/filipowm/boogi
    - text: React
      link: https://reactjs.org
  ignoreIndex: false
  poweredBy:
    trademark: "/assets/gatsby.png"
    name: GatsbyJS
    link: https://www.gatsbyjs.org
pwa:
  enabled: true
  manifest:
    display: standalone
    crossOrigin: anonymous
    icon: "/assets/favicon.png"

social:
  github: https://github.com/CitizenAERG/boogi
  linkedin: linkedin url
  twitter: twitter url

features:
  darkMode:
    enabled: true
    default: false
  editOnRepo:
    location: https://github.com/CitizenAERG/boogi
    type: github
    editable: true
  mermaid:
    language: "mermaid"
    theme: "dark"
    options:
    width: 400
    height: 300
  pageProgress:
    enabled: true
    includePaths:
      - "/configuration/settingup/features"
    excludePaths:
      - "/"
    height: 3
    prependToBody: false
    color: "#A05EB5"
  previousNext:
    enabled: true
    arrowKeyNavigation: true
  propagateNetlifyEnv: true
  rss:
    enabled: true
    title: Futureworks
    showIcon: false
    copyright: "2021, CitizenAERG"
    webMaster: "CitizenAERG"
    managingEditor: "CitizenAERG"
    categories:
      - Docs as Code
      - GatsbyJS
    ttl: 60
    matchRegex: "^/"
    outputPath: "/rss.xml"
    generator: "boogi"
  scrollTop: true
  search:
    enabled: true
    engine: 'algolia'
    placeholder: 'Search'
    startComponent: 'input' # icon
    excerptSize: 8000
    debounceTime: 380
    snippetLength: 23
    hitsPerPage: 10
    showStats: true
    pagination:
      enabled: true
      totalPages: 10
      showPrevious: true
      showNext: true
  showMetadata: true
  toc:
    show: true
    depth: 4
  fullScreenMode:
    enabled: true
    hideHeader: true
    hideToc: true
    hideSidebar: true
